### ISSUE TITLE
Output a CSV with the failed emails.

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/node-emails-from-csv#2]
Having a failure CSV would be great I guess. We can perhaps then write a script for resending to the failed ones. Then automating it eventually.
But for now, writing the failures in output is the task.

**Comment by siraj1044** [comment]
Yep, sounds good.

**Comment by AhsanAyaz** [comment]
Fixed by https://github.com/AhsanAyaz/node-emails-from-csv/pull/3
